fix: [directory] sort the entry at project tree
linuxdeepin/deepin-unioncode pull request #1015
Opened 2024-12-06 08:58 UTC by LiHua000

Log: as title

2024-12-09 02:08 UTC, Kakueeen approved these changes

2024-12-10 02:02 UTC, deepin-mozart requested changes

2024-12-10 02:02 UTC, deepin-mozart commented on src/services/project/directoryasynparse.cpp
> +            if (QFileInfo(a->toolTip()).isDir() && !QFileInfo(b->toolTip()).isDir()) return true;
tooltip是用于提示的信息，不建议用于判断。可以在item添加一个路径属性来解决这个问题

2024-12-12 12:08 UTC, Kakueeen commented
可以关了，我这边一起改了

2024-12-12 12:33 UTC, deepin-mozart commented
本次修改已在其它提交合入，可以关闭

2024-12-12 12:33 UTC, closed without merging