fix: Replace ui with DTk when closing a window with unsaved changes
linuxdeepin/deepin-unioncode pull request #299
Opened 2023-12-28 09:23 UTC by tsl115

当关闭编辑区中，仍有未修改内容的窗口时，会导致程序崩溃，修复了这个问题，并且替换了提示窗口的ui

2023-12-28 09:41 UTC, N0rthHXD requested changes

2023-12-28 09:41 UTC, N0rthHXD commented on src/plugins/codeeditor/textedittabwidget/textedittabwidget.cpp
> +   // QTimer::singleShot(100, [=](){edit->cleanIsSaveText();});
不能把这个注释掉，这里edit空是符合逻辑的，在上边加个判断就行。

2023-12-29 02:28 UTC, tsl115 commented on src/plugins/codeeditor/textedittabwidget/textedittabwidget.cpp
> +   // QTimer::singleShot(100, [=](){edit->cleanIsSaveText();});
已修改，加了个判断，当edit判断为空或空指针的时候，就提前return

2024-01-02 02:42 UTC, deepin-mozart submitted a review, later dismissed

2024-01-02 06:24 UTC, closed without merging