feat: FindToolBar ui modification
linuxdeepin/deepin-unioncode pull request #302
Opened 2023-12-29 07:28 UTC by tsl115

FindToolBar ui modification

2023-12-29 08:16 UTC, LiHua000 requested changes

2023-12-29 08:16 UTC, LiHua000 commented on src/plugins/find/findtoolbar.cpp
> -    connect(advancedBtn, &QAbstractButton::clicked, this, &FindToolBar::advancedSearch);
这个接口如果没地方用了，接口的声明和实现也应该删了

2023-12-29 08:20 UTC, LiHua000 requested changes

2023-12-29 08:20 UTC, LiHua000 commented on src/plugins/find/findtoolbar.cpp
> +    hLayout->addWidget(blankWidget);
这个blankWidget是干吗的，要加间隔的话直接用margin等属性是不是好一点，加空窗口不太好

2023-12-29 08:42 UTC, tsl115 commented on src/plugins/find/findtoolbar.cpp
> -    connect(advancedBtn, &QAbstractButton::clicked, this, &FindToolBar::advancedSearch);
已修改

2023-12-29 08:44 UTC, tsl115 commented on src/plugins/find/findtoolbar.cpp
> +    hLayout->addWidget(blankWidget);
已修改

2023-12-29 08:51 UTC, N0rthHXD requested changes

2023-12-29 08:51 UTC, N0rthHXD commented on src/plugins/find/findtoolbar.cpp
> +#include <DIconButton>
头文件DTK和QT的分开，这个放上边

2023-12-29 08:51 UTC, N0rthHXD commented on src/plugins/find/findtoolbar.cpp
>  #define OPERATOR_WIDGET_WIDTH (400)
这两个宏不用删了

2023-12-29 08:55 UTC, tsl115 commented on src/plugins/find/findtoolbar.cpp
> +#include <DIconButton>
已修改

2023-12-29 08:55 UTC, tsl115 commented on src/plugins/find/findtoolbar.cpp
>  #define OPERATOR_WIDGET_WIDTH (400)
已修改

2024-01-02 02:07 UTC, deepin-mozart submitted a review, later dismissed

2024-01-02 09:14 UTC, deepin-mozart approved these changes

2024-01-02 09:15 UTC, deepin-mozart approved these changes

2024-01-02 10:14 UTC, LiHua000 approved these changes

2024-01-02 10:15 UTC, merged