refactor: Refactoring the editor
linuxdeepin/deepin-unioncode pull request #331
Opened 2024-01-17 09:31 UTC by Kakueeen

1.Code refactoring
2.Optimized interaction logic

Log: Code refactoring

2024-01-17 10:05 UTC, LiHua000 requested changes

2024-01-17 10:05 UTC, LiHua000 commented on src/plugins/codeeditor/CMakeLists.txt
> +#    )
这里用下面的方式来添加文件了，这上面注释起来的部分就都没用，可以直接删掉了吧

2024-01-18 01:52 UTC, deepin-mozart commented on src/plugins/codeeditor/gui/private/texteditor_p.cpp
> +    // 显示行号
注释统一用英文

2024-01-18 01:53 UTC, deepin-mozart commented on src/plugins/codeeditor/gui/private/texteditor_p.cpp
> +        q->setCaretForegroundColor(QColor("#FFFFFF"));
这里建议把颜色进行统一定义，比如定义灰色=XXX

2024-01-18 02:28 UTC, LiHua000 approved these changes

2024-01-18 05:35 UTC, merged