fix: configuration file
linuxdeepin/deepin-unioncode pull request #6
Opened 2023-07-17 09:08 UTC by HJC5305

1. modify the toolchain configuration file
2. modify control file

log: fix bug

2023-07-17 09:09 UTC, HJC5305 commented
I have read the CLA Document and I hereby sign the CLA.

2023-07-17 09:15 UTC, HJC5305 commented
I have read the CLA Document and I hereby sign the CLA.

2023-07-18 05:55 UTC, deepin-mozart requested changes
请按照评论进行修改

2023-07-18 05:55 UTC, deepin-mozart commented on src/scripts/toolchain.sh
> +	CMAKE_VERSIONS=($CMAKE_VERSIONS)
这里需要删除

2023-07-18 05:55 UTC, deepin-mozart commented on src/scripts/toolchain.sh
> +	DEBUGGERS=($DEBUGGERS)
这里要改个名字

2023-07-18 05:55 UTC, deepin-mozart commented on src/scripts/toolchain.sh
> +	DEBUGGERS=$(find /usr/bin -name gdb \
这里不用改为/usr/bin

2023-07-18 06:10 UTC, closed without merging