fix: [core] dividing line between the navigation bar and the dockwidge
linuxdeepin/deepin-unioncode pull request #654
Opened 2024-06-12 07:09 UTC by fuyou158

added dividing line
Log: fix issues

2024-06-12 07:17 UTC, deepin-mozart requested changes

2024-06-12 07:17 UTC, deepin-mozart commented on src/plugins/core/uicontroller/mainwindow.cpp
> +        auto p = tb->palette();
这里的代码和451~453的重复了，建议提成函数

2024-06-12 07:35 UTC, fuyou158 commented on src/plugins/core/uicontroller/mainwindow.cpp
> +        auto p = tb->palette();
已修改

2024-06-12 09:02 UTC, LiHua000 approved these changes

2024-06-12 09:08 UTC, fuyou158 commented on src/plugins/core/uicontroller/mainwindow.cpp
> +    tb->setContentsMargins(0, 0, 2, 0);
已删除444行

2024-06-14 02:14 UTC, LiHua000 approved these changes

2024-06-14 02:27 UTC, Kakueeen approved these changes

2024-06-14 05:46 UTC, merged