fix: [plugin] modified ui
linuxdeepin/deepin-unioncode pull request #710
Opened 2024-06-24 07:29 UTC by fuyou158

Log: fixed some ui issues in plugin

Bug: https://pms.uniontech.com/bug-view-258793.html

2024-06-24 09:43 UTC, LiHua000 approved these changes

2024-06-25 01:54 UTC, deepin-mozart requested changes

2024-06-25 01:54 UTC, deepin-mozart commented on src/plugins/core/modules/pluginmanagermodule.cpp
> +            windowService->setDockHeaderName(MWMTA_PLUGINS, tr("Plugins"));
我看设计图写的是扩展，这个Plugins是否需要改为Extensions

2024-06-25 02:09 UTC, fuyou158 commented on src/plugins/core/modules/pluginmanagermodule.cpp
> +            windowService->setDockHeaderName(MWMTA_PLUGINS, tr("Plugins"));
已改为Extensions

2024-06-25 02:14 UTC, merged