fix: [project] dialog adjustsize
linuxdeepin/deepin-unioncode pull request #851
Opened 2024-08-01 09:32 UTC by LiHua000

Log: as title

2024-08-01 10:38 UTC, deepin-mozart requested changes

2024-08-01 10:38 UTC, deepin-mozart commented on src/plugins/project/projectcore.cpp
> +            Qt::DirectConnection);
确认下这里的格式是否正确

2024-08-01 10:40 UTC, Kakueeen approved these changes

2024-08-02 01:41 UTC, LiHua000 commented on src/plugins/project/projectcore.cpp
> +            Qt::DirectConnection);
clang自动改的。  应该是没问题的。逻辑是会把最后一个参数换行单独放

2024-08-02 02:14 UTC, deepin-mozart approved these changes

2024-08-02 02:14 UTC, merged