feat: [Ai] Add basic RAG capabilities, optimize Codegeex
linuxdeepin/deepin-unioncode pull request #914
Opened 2024-09-24 09:14 UTC by LiHua000

Log: as title

2024-09-25 02:04 UTC, deepin-mozart requested changes

2024-09-25 02:04 UTC, deepin-mozart commented on src/plugins/codegeex/codegeexmanager.cpp
> +    bool failed = false;
failed变量的作用域是当前函数，确定下用到的地方是否会析构

2024-09-25 02:05 UTC, deepin-mozart requested changes

2024-09-25 02:05 UTC, deepin-mozart commented on src/scripts/rag/models/all-MiniLM-L6-v2/onnx/model_quantized.onnx
这个文件应该放到assets目录

2024-09-25 08:29 UTC, LiHua000 commented on src/plugins/codegeex/codegeexmanager.cpp
> +    QMetaObject::invokeMethod(this, [=, scriptPath]() {
已有的接口没法直接调用脚本文件进行安装。需要额外写安装类来实现

2024-09-26 02:31 UTC, deepin-mozart approved these changes

2024-09-26 02:31 UTC, deepin-mozart commented on src/plugins/codegeex/copilot.cpp
> +        generateTimer->start(500);
不用stop，start会重新开始：If the timer is already running, it will be stopped and restarted.

2024-09-26 02:31 UTC, merged