feat: [codegeex] modified ui of codegeex
linuxdeepin/deepin-unioncode pull request #963
Opened 2024-10-29 12:06 UTC by LiHua000

Log: as title

2024-10-30 03:29 UTC, Kakueeen approved these changes

2024-10-30 03:50 UTC, deepin-mozart requested changes

2024-10-30 03:50 UTC, deepin-mozart commented on src/plugins/codegeex/widgets/intropage.h
> +    int minimumWidth;
规范：赋初值

2024-10-30 03:50 UTC, deepin-mozart commented on src/plugins/codegeex/widgets/intropage.h
> +#include <DPushButton>
规范：DTK的头文件在QT上面

2024-10-30 03:50 UTC, deepin-mozart commented on src/plugins/codegeex/codegeex.qrc
> +        <file>builtin/texts/codegeex_project_chat_16px.svg</file>
规范：新加的图标名字都加上前缀uc_

2024-10-31 03:47 UTC, Kakueeen approved these changes

2024-10-31 05:24 UTC, deepin-mozart approved these changes

2024-10-31 05:24 UTC, merged