refactor: [settings] migrate config storage to unified settings system
linuxdeepin/deepin-unioncode pull request #991
Opened 2024-11-14 02:15 UTC by Kakueeen

Refactored configuration storage mechanism across multiple components to use
the unified settings system:

- Migrated language settings from file-based to settings-based storage
- Updated CodeGeeX configuration to use OptionManager
- Refactored profile settings to use centralized storage
- Added compatibility code for smooth transition from old storage format
- Cleaned up deprecated file-based storage methods

The changes improve configuration management consistency and maintainability
by centralizing all settings into a single system.

Log: refactored configuration storage to use unified settings system

2024-11-16 04:00 UTC, LiHua000 approved these changes

2024-11-16 05:30 UTC, deepin-mozart requested changes

2024-11-16 05:30 UTC, deepin-mozart commented on src/plugins/option/optioncore/mainframe/profilesettingwidget.cpp
> +[[deprecated("-------------存在兼容代码需要删除")]] QString ProfileSettingWidget::languageFilePath()
建议使用：Q_DECL_DEPRECATED_X

2024-11-21 06:52 UTC, deepin-mozart approved these changes

2024-11-21 06:52 UTC, merged