feat: [codegeex] Optimize the UI of the Q&A interface and display mor…
linuxdeepin/deepin-unioncode pull request #996
Opened 2024-11-15 09:36 UTC by LiHua000

…e information.

log: as title

2024-11-15 09:47 UTC, Kakueeen commented on src/plugins/codegeex/widgets/inputeditwidget.cpp
> +                                                        QString::number(selectedRange.end.column));
行和列应该都是从0计数的，这里显示需要+1不呢？

2024-11-15 09:47 UTC, Kakueeen commented on src/plugins/codegeex/widgets/inputeditwidget.cpp
> +        return DTextEdit::focusInEvent(e);
这个判断可以提前

2024-11-16 03:37 UTC, deepin-mozart requested changes

2024-11-16 03:37 UTC, deepin-mozart commented on src/plugins/codegeex/CMakeLists.txt
> +pkg_check_modules(CMARK REQUIRED libcmark)
确认：这个依赖是否应该写到control

2024-11-16 03:37 UTC, deepin-mozart commented on src/plugins/codegeex/codegeex/askapi.cpp
> +        QJsonObject result = CodeGeeXManager::instance()->query(currentProjectPath, queryText.remove("@CodeBase"), 50);
这些业务功能不应该放到这里，建议在上一层加个封装

2024-11-16 03:54 UTC, LiHua000 commented on src/plugins/codegeex/CMakeLists.txt
> +pkg_check_modules(CMARK REQUIRED libcmark)
controll中已有，是之前editor就用到了

2024-11-16 03:58 UTC, LiHua000 commented on src/plugins/codegeex/codegeex/askapi.cpp
> +        QJsonObject result = CodeGeeXManager::instance()->query(currentProjectPath, queryText.remove("@CodeBase"), 50);
后续在输入框类中统一修改

2024-11-16 05:35 UTC, deepin-mozart approved these changes

2024-11-16 05:35 UTC, merged